apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: jaegertracing
    meta.helm.sh/release-namespace: observability
  creationTimestamp: "2024-07-14T17:00:05Z"
  generation: 3
  labels:
    app: cassandra
    app.kubernetes.io/managed-by: Helm
    chart: cassandra-0.15.3
    heritage: Helm
    release: jaegertracing
  name: jaegertracing-cassandra
  namespace: observability
  resourceVersion: "85439"
  uid: 641048a9-42c1-4b50-a01f-9e0680499287
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
      release: jaegertracing
  serviceName: jaegertracing-cassandra
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-07-14T11:23:37-06:00"
      creationTimestamp: null
      labels:
        app: cassandra
        release: jaegertracing
    spec:
      containers:
      - env:
        - name: CASSANDRA_SEEDS
          value: jaegertracing-cassandra-0.jaegertracing-cassandra.observability.svc.cluster.local
        - name: MAX_HEAP_SIZE
          value: 2048M
        - name: HEAP_NEWSIZE
          value: 512M
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        - name: CASSANDRA_CLUSTER_NAME
          value: jaeger
        - name: CASSANDRA_DC
          value: dc1
        - name: CASSANDRA_RACK
          value: rack1
        - name: CASSANDRA_START_RPC
          value: "false"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: cassandra:3.11.6
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - exec nodetool decommission
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nodetool status
          failureThreshold: 3
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: jaegertracing-cassandra
        ports:
        - containerPort: 7000
          name: intra
          protocol: TCP
        - containerPort: 7001
          name: tls
          protocol: TCP
        - containerPort: 7199
          name: jmx
          protocol: TCP
        - containerPort: 9042
          name: cql
          protocol: TCP
        - containerPort: 9160
          name: thrift
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nodetool status | grep -E "^UN\s+${POD_IP}"
          failureThreshold: 3
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: 250m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
  updateStrategy:
    type: OnDelete
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: jaegertracing-cassandra-77c7c6f7cd
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updateRevision: jaegertracing-cassandra-f888699d8
