{
 "title": "ASPACE",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stack",
    "label": "stack",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"aspace\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Aspace - logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"aspace\", namespace=\"aspace\"}"
    }
   ]
  },
  {
   "title": "Aspace - 2nd Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"aspace\",container=\"aspace\",filename=\"/var/log/pods/aspace_aspace-544678d5d4-78gw9_619a2ca8-4d19-4d43-8cb0-bef506b9b2af/aspace/0.log\"}"
    }
   ]
  }
 ]
}