{
 "title": "DAIS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"dais\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "DTS - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"dts\", namespace=\"dais\"}"
    }
   ]
  },
  {
   "title": "Notifier - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"notifier\", namespace=\"dais\"}"
    }
   ]
  },
  {
   "title": "RabbitMQ-Email-Notifier - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"rabbitmq-email-notifier\", namespace=\"dais\"}"
    }
   ]
  },
  {
   "title": "Transfer Service - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{app=\"transfer-service\", namespace=\"dais\"}"
    }
   ]
  }
 ]
}