{
 "title": "DRS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"drs\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "DRS2 Service - logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"drs2-services\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Webadmin - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"drs-webadmin\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "drs BATCHES",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"drs2-services\"} |= `/drs2qa/drsfs/dropbox`"
    }
   ]
  },
  {
   "title": "Wordshack - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=\"wordshack\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "OCFL-Storage - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{app=\"ocfl-storage\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS FITS - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{app=\"drs-fits\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-File-API - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{app=\"drs-file-api\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-File-Locator - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "{app=\"drs-file-locator\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Verify - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{app=\"drs-verify\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Set-Manager - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{app=\"set-manager\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Clam-AV - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{app=\"drs-clam\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Decrypt - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "{app=\"drs-decrypt\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Encrypt - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "{app=\"drs-encrypt\", namespace=\"drs\"}"
    }
   ]
  },
  {
   "title": "DRS-Webadmin - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "{app=\"drs-webadmin\", namespace=\"drs\"}"
    }
   ]
  }
 ]
}