{
 "title": "EDA",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"eda\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "EDA - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"eda\", namespace=\"eda\"}"
    }
   ]
  },
  {
   "title": "EDA IIP - Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"eda-iip\", namespace=\"eda\"}"
    }
   ]
  }
 ]
}