{
 "title": "ETD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"etd\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "etd-alma-drs - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"etd-alma-drs-holding-service\", namespace=\"etd\"}"
    }
   ]
  },
  {
   "title": "etd-alma-monitor - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"etd-alma-monitor-service\", namespace=\"etd\"}"
    }
   ]
  },
  {
   "title": "etd-alma - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"etd-alma-service\", namespace=\"etd\"}"
    }
   ]
  },
  {
   "title": "etd-dash - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{app=\"etd-dash-service\", namespace=\"etd\"}"
    }
   ]
  }
 ]
}