{
 "title": "FTS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"fts\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "API - Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"api\", namespace=\"fts\"}"
    }
   ]
  },
  {
   "title": "Loader - Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"loader\", namespace=\"fts\"}"
    }
   ]
  },
  {
   "title": "UI - Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{app=\"ui\", namespace=\"fts\"}"
    }
   ]
  }
 ]
}