{
 "title": "IDS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"ids\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "IDS - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"ids\", namespace=\"ids\"}"
    }
   ]
  },
  {
   "title": "IIIF - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"iiif\", namespace=\"ids\"}"
    }
   ]
  },
  {
   "title": "IIIF-Updater - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"iiif-updater\", namespace=\"ids\"}"
    }
   ]
  },
  {
   "title": "PDS - Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{app=\"pds\", namespace=\"ids\"}"
    }
   ]
  }
 ]
}