{
 "title": "LibraryCloud",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"librarycloud\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "LC Collections - Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"lc-collections\", namespace=\"librarycloud\"}"
    }
   ]
  },
  {
   "title": "LC collectionsbuilder - Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"lc-collectionsbuilder\", namespace=\"librarycloud\"}"
    }
   ]
  },
  {
   "title": "LC CSV - Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"lc-csv\", namespace=\"librarycloud\"}"
    }
   ]
  },
  {
   "title": "LC Ingest - Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"lc-ingest\", namespace=\"librarycloud\"}"
    }
   ]
  },
  {
   "title": "LC Oai - Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{app=\"lc-oai\", namespace=\"librarycloud\"}"
    }
   ]
  }
 ]
}