{
 "title": "MPS-Viewer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"mps-viewer\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{namespace=\"mps-viewer\"} != `XDS`"
    }
   ]
  },
  {
   "title": "Rates for app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate({app=\"mps-viewer\"}[$__auto])"
    }
   ]
  }
 ]
}