{
 "title": "NRS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"nrs\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"nrs\"}"
    }
   ]
  },
  {
   "title": "Logs requests",
   "type": "logs",
   "description": "IP addresses, source of request.",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"nrs\"} |= `x_forwarded_for` | json | line_format \"{{.x_forwarded_for}}\""
    }
   ]
  }
 ]
}