{
 "title": "COLLEX",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=\"collex\"} |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Search API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"collex-llm-api\", namespace=\"collex\"}"
    }
   ]
  },
  {
   "title": "Forntend- Nexjs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"collex-public-frontend-nextjs\", namespace=\"collex\"}"
    }
   ]
  },
  {
   "title": "Search API",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"collex-search-api\", namespace=\"collex\"}"
    }
   ]
  }
 ]
}